title: "<name>"
theme: "eon"
baseURL: "https://<owner>.github.io/<repo>"
#baseURL: 'http://localhost:8801'
# for multiple authors, see
# https://discourse.gohugo.io/t/site-author-usage/31459/8?u=coolaj86
Author:
  name: "<name>"
  email: "<email>"
copyright: "© <name>"
languageCode: "en-us"

Params:
  gravatar: true
  show_edit: "Suggest Edit"
  git_repo: "https://github.com/<owner>/<repo>"
  git_branch: "<branch>"
  git_host: "github"
  utterences_repo: "<owner>/<repo>"
  utterences_term: "pathname"
  enableGitInfo: true
  enableEmoji: true

markup:
  goldmark:
    renderer:
    # unsafe allows use of HTML and JavaScript in your Markdown
    # disable if your blog allows posts from untrusted authors
    unsafe: true
