# Simplified Docs at https://github.com/coolaj86/explore-github-actions/
name: Build GitHub Pages
on: [push]
jobs:
    Build-GitHub-Pages:
        runs-on: ubuntu-20.04
        env:
          GH_BASIC_AUTH: "x-access-token:${{ github.token }}"
          GH_TOKEN: "${{ github.token }}"
        steps:
            - run: echo "${{ github.event_name }} triggered ${{ github.repository }}#${{ github.ref }} to build on ${{ runner.os }} from ${{ github.workspace }} (cwd)"
            - name: Set Default Git Branch (to quiet warnings)
              run: git config --global init.defaultBranch main
            - name: Check out repository code
              uses: actions/checkout@v2
              with:
                #ref: main
                submodules: recursive
            - name: "Webi: Install 'node' and 'hugo', and update PATH"
              run: |
                bash ./scripts/install-deps.sh
                echo "${HOME}/.local/opt/node/bin" >> $GITHUB_PATH
            - run: hugo version
            - run: node --version
            - name: Add Git User
              run: |
                git config --global user.name 'Github Actions'
                git config --global user.email 'github-actions@users.noreply.github.com'
            - name: Template
              run: bash ./scripts/ga-template.sh
            - name: Build
              run: bash ./scripts/build.sh
            - name: Deploy
              run: bash ./scripts/deploy.sh
            - run: echo "Status ${{ job.status }}."
